// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://fpavemysfakxkfpersll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwYXZlbXlzZmFreGtmcGVyc2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODg5MzIsImV4cCI6MjA2OTI2NDkzMn0.4GKr7J2R7C8nYUN1uGam9ozLpkAzvo64JRpSIsQRC-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
