// Auto-generated by Supabase CLI. This file is gitignored.
// To generate your own: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/integrations/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: string };
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends string> = Record<string, never>;
export type TablesInsert<T extends string> = Record<string, never>;
export type TablesUpdate<T extends string> = Record<string, never>;
export type Enums<T extends string> = never;
export type CompositeTypes<T extends string> = never;
